### ISSUE TITLE
关于高斯的排序

### ISSUE THREAD

**Issue by zheng-chen777** [guikunchen/3DGS_NOTES#2]
在rasterizer_impl.cu中，使用SortPairs对高斯进行了排序，我想请问这里的排序就完成了对高斯所有属性的排序吗（包括，位置颜色等信息）。如果我对每个高斯新增了属性，那么是否要对新增的属性也进行相同的排序呀，如果需要的话要怎么做呢。期待大佬回复

**Comment by guikunchen** [comment]
> 在rasterizer_impl.cu中，使用SortPairs对高斯进行了排序，我想请问这里的排序就完成了对高斯所有属性的排序吗（包括，位置颜色等信息）。如果我对每个高斯新增了属性，那么是否要对新增的属性也进行相同的排序呀，如果需要的话要怎么做呢。期待大佬回复

不是根据高斯的属性进行排序的哈，是根据高斯的深度（相对于camera）进行排序的，便于后面并行渲染。新增属性不需要改动排序相关的代码，祝 work！

**Comment by zheng-chen777** [comment]
> > 在rasterizer_impl.cu中，使用SortPairs对高斯进行了排序，我想请问这里的排序就完成了对高斯所有属性的排序吗（包括，位置颜色等信息）。如果我对每个高斯新增了属性，那么是否要对新增的属性也进行相同的排序呀，如果需要的话要怎么做呢。期待大佬回复
> 
> 不是根据高斯的属性进行排序的哈，是根据高斯的深度（相对于camera）进行排序的，便于后面并行渲染。新增属性不需要改动排序相关的代码，祝 work！

好的，感谢！
