### ISSUE TITLE
关于高斯点的初始化

### ISSUE THREAD

**Issue by zheng-chen777** [guikunchen/3DGS_NOTES#3]
我在初始化高斯的时候使用了两部分点来初始化，我在渲染高斯的时候，通过我新增的属性过滤掉了其中一部分高斯不进行渲染，请问这是否等价于我在初始化的时候直接去掉对应的点，不初始化这部分高斯直接进行渲染的结果呢（在进行第一次loss.backward之前的结果，也就是只进行第一次前向过程的渲染结果理论上是否相同呢）。我现在计算出来的结果有所差异，不太清楚是从原理上就存在不同，还是代码的问题，希望大佬能够解答

**Comment by guikunchen** [comment]
先把初始化这个概念去掉，跟初始化无关。假设所有高斯分为两类，1) 一开头就直接去掉某一类高斯，不做 splatting；2) 做了 splatting，但某一类高斯不进行渲染，这两种前向过程得到的结果应该是一样的。
